[workspace]
members = [
    "bernard",
    "bernard-cli"
]

[patch."https://github.com/diesel-rs/diesel"]
diesel = { git = "https://github.com/m-rots/diesel", branch = "sqlite-error-handling" }
diesel_migrations = { git = "https://github.com/m-rots/diesel", branch = "sqlite-error-handling" }