# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "bernard/src/schema.rs"
patch_file = "bernard/src/schema.patch"
with_docs = true