name: Test
on: [push, pull_request]

jobs:
  test:
    name: CI Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1

      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test